workers=24

if [ -n "$1" ]; then

  batch_flavor="$1"
  differential_variable="$2"

  law run Trees2WS --workers $workers --variable $differential_variable --year 2023 --batch-flavor $batch_flavor; law run Background --workers $workers --variable $differential_variable --year 2023 --batch-flavor $batch_flavor; law run FTest --workers $workers --variable $differential_variable --year 2023 --batch-flavor $batch_flavor; law run CalcPhotonSyst --workers $workers --variable $differential_variable --year 2023 --batch-flavor $batch_flavor; law run SignalFit --workers $workers --variable $differential_variable --year 2023 --batch-flavor $batch_flavor; law run SignalPackaging --workers $workers --variable $differential_variable --year 2023 --batch-flavor $batch_flavor; law run MakeYields --workers $workers --variable $differential_variable --year 2023 --batch-flavor $batch_flavor; law run MakeDatacard --workers $workers --variable $differential_variable --year 2023 --batch-flavor $batch_flavor --version ${differential_variable}_v1; law run PrepareTheDirectory --variable $differential_variable --year 2023 --batch-flavor $batch_flavor --version ${differential_variable}_v1; law run RunText2Workspace --workers $workers --variable $differential_variable --year 2023 --batch-flavor $batch_flavor --version ${differential_variable}_v1; law run CreateAsimovFitFirstStep --workers $workers --variable $differential_variable --year 2023 --batch-flavor $batch_flavor; law run CreateAsimovFit --workers $workers --variable $differential_variable --year 2023 --batch-flavor $batch_flavor --version ${differential_variable}_v1
else
  # law run RunText2Workspace --workers $workers
  law run Trees2WS --workers $workers --year 2023 --batch-flavor $batch_flavor; law run Background --workers $workers --year 2023 --batch-flavor $batch_flavor; law run FTest --workers $workers --year 2023 --batch-flavor $batch_flavor; law run CalcPhotonSyst --workers $workers --year 2023 --batch-flavor $batch_flavor; law run SignalFit --workers $workers --year 2023 --batch-flavor $batch_flavor; law run SignalPackaging --workers $workers --year 2023 --batch-flavor $batch_flavor; law run MakeYields --workers $workers --year 2023 --batch-flavor $batch_flavor; law run MakeDatacard --workers $workers --year 2023 --batch-flavor $batch_flavor --version v1; law run PrepareTheDirectory --year 2023 --batch-flavor $batch_flavor --version v1; law run RunText2Workspace --workers $workers --year 2023 --batch-flavor $batch_flavor --version v1; law run CreateAsimovFitFirstStep --workers $workers --year 2023 --batch-flavor $batch_flavor; law run CreateAsimovFit --workers $workers --year 2023 --batch-flavor $batch_flavor --version v1
fi