executable = trees.sh
arguments  = $(ProcId)
output     = /eos/user/p/pkrueper/HiggsDNA_and_FinalFits_tutorial24/FF_standalone/src/flashggFinalFit/Trees2WS/logs/condor_signalFit_Run3STXS_preBPix.$(ClusterId).$(ProcId).out
error      = /eos/user/p/pkrueper/HiggsDNA_and_FinalFits_tutorial24/FF_standalone/src/flashggFinalFit/Trees2WS/logs/condor_signalFit_Run3STXS_preBPix.$(ClusterId).$(ProcId).err
log      = /eos/user/p/pkrueper/HiggsDNA_and_FinalFits_tutorial24/FF_standalone/src/flashggFinalFit/Trees2WS/logs/condor_signalFit_Run3STXS_preBPix.$(ClusterId).$(ProcId).log
transfer_output_files = "" 

request_memory = 12GB

# Send the job to Held state on failure
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

# Periodically retry the jobs every 10 minutes, up to a maximum of 5 retries.
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)

+JobFlavour = "longlunch"
queue 1
