# Config file: options for signal fitting

outputFolder: '/net/data_cms3a-1/wrabetz/CMSSW_14_1_0_pre4/src/flashggFinalFit/output_2023_PTH/'

inputFiles:
  # Trees2WS
  Trees2WSData: '/net/data_cms3a-2/nobackup/group_JE_CMS/Hgg_PartialRun3/stat_analysis/differential/2025_07_18/PTH/allData_2023.root'
  Trees2WS: '/net/data_cms3a-2/nobackup/group_JE_CMS/Hgg_PartialRun3/stat_analysis/differential/2025_07_18/PTH/root/'

backgroundScriptCfg:
  # Setup
  cats: 'auto' # auto: automatically inferred from input ws
  catOffset: 0 # add offset to category numbers (useful for categories from different allData.root files)
  ext: 'earlyAnalysis_PTH' # extension to add to output directory
  # year: '2023' # Use combined when merging all years in category (for plots)
  execution: 'htcondor'
  batchPartition: "short" # Slurm partition to use for job submission
  batchMemory: 4000 # Slurm memory to use for job submission
  batchMaxRuntime: "01:00:00" # Slurm max runtime to use

trees2wsCfg:
  inputTreeDir: 'DiphotonTree' # Name of RooDirectory storing input tree

  apply_mass_cut: False # Apply cut on CMS_hgg_mass
  mass_cut_range: '100,180' # CMS_hgg_mass cut range
  doSTXSSplitting: False # Split output WS per STXS bin
  doDiffSplitting: True # Split output WS per differential bin
  doInOutSplitting: False # Split output WS into in/out fiducial based on some variable in the input trees (to be improved).
  doSystematics: True # Add systematics datasets to output WS

  # Variables to be added to dataframe: use wildcard * for common strings
  mainVars:
    - "CMS_hgg_mass"
    - "weight"
    - "weight_central"
    - "dZ"
    - "*Up"
    - "*Down"
    - "fiducialGeometricFlag"
    - "diffVariable_GenPTH"
  
  dataVars:
    - "CMS_hgg_mass"
    - "weight" # Vars to be added for data
    
  stxsVar: ''
  diffVar: 'diffVariable_GenPTH'
  notagVars: [] # Vars to add to NOTAG RooDataset
  
  systematicsVars:
    - "CMS_hgg_mass"
    - "weight"
    - "fiducialGeometricFlag"
    - "diffVariable_GenPTH"
  
  theoryWeightContainers:
    weight_LHEPdf: 101
    weight_LHEScale: 9

  # List of systematics: use string YEAR for year-dependent systematics
  systematics:
    - "ScaleEB"
    - "ScaleEE"
    - "Smearing"
    - "Material"
    - "FNUF"
    - "energyErrShift"
    - "JerSyst"
    - "JecSystTotal"

  cats: 'auto'

  execution: 'htcondor'
  batchPartition: "short" # Slurm partition to use for job submission
  batchMemory: 4000 # Slurm memory to use for job submission
  batchMaxRuntime: "01:00:00" # Slurm max runtime to use

signalScriptCfg_2023_preBPix:
  # Setup
  procs: 'auto' # if auto: inferred automatically from filenames (requires names to be of form *pythia8_{PROC}.root)
  cats: 'auto' # if auto: inferred automatically from (0) workspace
  ext: 'earlyAnalysis_PTH_2023preBPix' # output directory extension
  analysis: 'earlyAnalysisDiffPt' # To specify replacement dataset and XS*BR mapping (defined in ./tools/replacementMap.py and ./tools/XSBRMap.py respectively)
  year: '2023preBPix' # Use 'combined' if merging all years: not recommended
  massPoints: '120,125,130' # You can now run with a single mass point if necessary
  replacementThreshold: '50'
  # Photon shape systematics  
  scales: 'ScaleEE,ScaleEB' # separate nuisance per year
  scalesCorr: 'FNUF,Material' # correlated across years
  scalesGlobal: 'NonLinearity,Geant4' # affect all processes equally, correlated across years
  smears: 'Smearing' # separate nuisance per year

  doPlots: True

  beamspotWidthData: '3.703'
  beamspotWidthMC: '3.597'


  # Job submission options
  execution: 'htcondor'
  batchPartition: "short" # Slurm partition to use for job submission
  batchMemory: 4000 # Slurm memory to use for job submission
  batchMaxRuntime: "01:00:00" # Slurm max runtime to use

signalScriptCfg_2023_postBPix:
  # Setup
  procs: 'auto' # if auto: inferred automatically from filenames (requires names to be of form *pythia8_{PROC}.root)
  cats: 'auto' # if auto: inferred automatically from (0) workspace
  ext: 'earlyAnalysis_PTH_2023postBPix' # output directory extension
  analysis: 'earlyAnalysisDiffPt' # To specify replacement dataset and XS*BR mapping (defined in ./tools/replacementMap.py and ./tools/XSBRMap.py respectively)
  year: '2023postBPix' # Use 'combined' if merging all years: not recommended
  massPoints: '120,125,130' # You can now run with a single mass point if necessary
  replacementThreshold: '50'
  # Photon shape systematics  
  scales: 'ScaleEE,ScaleEB' # separate nuisance per year
  scalesCorr: 'FNUF,Material' # correlated across years
  scalesGlobal: 'NonLinearity,Geant4' # affect all processes equally, correlated across years
  smears: 'Smearing' # separate nuisance per year

  doPlots: True

  beamspotWidthData: '3.737'
  beamspotWidthMC: '3.597'

  # Job submission options
  execution: 'htcondor'
  batchPartition: "short" # Slurm partition to use for job submission
  batchMemory: 4000 # Slurm memory to use for job submission
  batchMaxRuntime: "01:00:00" # Slurm max runtime to use

packaged_2023:
  cats: 'auto' # if auto: inferred automatically from (0) workspace
  massPoints: '120,125,130' # You can now run with a single mass point if necessary
  mergeYears: True # Merges the eras
  ext: ''
  execution: 'htcondor'
  batchPartition: "short" # Slurm partition to use for job submission
  batchMemory: 4000 # Slurm memory to use for job submission
  batchMaxRuntime: "01:00:00" # Slurm max runtime to use

datacard_yields:
  cats: 'auto' # if auto: inferred automatically from (0) workspace
  procs: 'auto' # if auto: inferred automatically from (0) workspace
  ext: 'earlyAnalysis' # Extension for saving
  # inputWSDirMap: '2023preBPix,2023postBPix'
  sigModelWSDir: './Models_PTH/signal' # Input signal model WS directory
  bkgModelWSDir: './Models_PTH/background' # Input background model WS directory
  bkgModelExt: 'multipdf' # Extension used when saving background model
  doSystematics: True # Include systematics calculations and add to datacard
  mergeYears: True # Merge category across years
  skipZeroes: True # Skip signal processes with 0 sum of weights
  ignore_warnings: True # Skip errors for missing systematics. Instead output warning message
  mass: '125' # Input workspace mass
  skipBkg: False # Only add signal processes to datacard
  bkgScaler: 1. # Add overall scale factor for background
  skipCOWCorr: True # Skip centralObjectWeight correction for events in acceptance. Use if no centralObjectWeight in workspace
  execution: 'htcondor'
  batchPartition: "short" # Slurm partition to use for job submission
  batchMemory: 4000 # Slurm memory to use for job submission
  batchMaxRuntime: "01:00:00" # Slurm max runtime to use

datacard:
  # For pruning processes
  prune: True # Prune proc x cat which make up less than pruneThreshold (default 0.1%) of given total category
  pruneThreshold: 0.001 # Threshold with which to prune proc x cat as fraction of total category yield (default=0.1%)
  doTrueYield: True # For pruning: use true number of expected events for proc x cat i.e. Product(XS,BR,eff*acc,lumi). If false then will use nominal_yield (i.e. sumEntries)
  analysis: 'earlyAnalysis' # Analysis extension: required for doTrueYield (see ./tools/XSBR.py for example)

  # For yield/systematics:
  skipCOWCorr: True # Skip centralObjectWeight correction for events in acceptance
  doSystematics: True # Include systematics calculations and add to datacard
  doMCStatUncertainty: True # Add uncertainty for MC stats
  doSTXSMerging: False # Calculate additional migrations uncertainties for merged STXS bins (for 'mnorm' tier in systematics)
  doSTXSScaleCorrelationScheme: False # Partially de-correlate scale uncertainties for different phase space regions

  # For output:
  saveDataFrame: False # Save final dataframe as pkl file
  output: 'Datacard_PTH_2023' # Datacard name

datacard_clean:
  factor: 10000 # Factor beyond which uncertainty is considered incorrect and is removed
  removeDoubleSided: False # Remove any nuisances which are listed as antisymmetric but both values point the same way
  removeNonDiagonal: False # Remove any nuisances which are affect processes unimportant in that category
  symmetrizeNuisance: 'CMS_hgg_SigmaEOverEShift,CMS_hgg_scale_0_shape,CMS_hgg_scale_1_shape,CMS_hgg_scale_3_shape' # Symmetrizes asymmetric nuisance. Enter in the format nuisance1,nuisance2,nuisance3,etc.
  verbose: False # Spit out all the cleaning being done

combine_fit:
  asimov_numPoints: 100 # Number of points the Asimov generator should generate for the NLL scan
  unblindedFit_numPoints: 100 
  setParameterRange: "r=0,3"
  execution: 'htcondor'
  batchPartition: "short" # Slurm partition to use for job submission
  batchMemory: 4000 # Slurm memory to use for job submission
  batchMaxRuntime: "01:00:00" # Slurm max runtime to use

combine_impacts:
  exclude: "" # Nuisances that should be excluded from the impact computation
  not_show_POI: True
  execution: 'htcondor'
  batchPartition: "short" # Slurm partition to use for job submission
  batchMemory: 4000 # Slurm memory to use for job submission
  batchMaxRuntime: "01:00:00" # Slurm max runtime to use

combine_hesse:
  execution: 'htcondor'
  batchPartition: "short" # Slurm partition to use for job submission
  batchMemory: 4000 # Slurm memory to use for job submission
  batchMaxRuntime: "01:00:00" # Slurm max runtime to use

combine_mggToys:
  nToys: 1000 # Number of toys = nToys * 10
  loadSnapshot: 'MultiDimFit'
  doBands: True
  execution: 'htcondor'
  batchPartition: "short" # Slurm partition to use for job submission
  batchMemory: 4000 # Slurm memory to use for job submission
  batchMaxRuntime: "01:00:00" # Slurm max runtime to use

spectra:
  no_preliminary: True # Flag that determines, if Preliminary label should be printed.
  ggh_xs: "fidXS_PTH_ggH"
  vbf_xs: "fidXS_PTH_VBFH"
  vh_xs: "fidXS_PTH_VH"
  tth_xs: "fidXS_PTH_ttH"
  xh_xs: "fidXS_PTH_xH"
  ggh_powheg_xs: "fidXS_PTH_ggH_powheg"
  ggh_no_nnlops_xs: "fidXS_PTH_ggH_genWeight"
  underflow_bin_normalized: False # Underflow bin normalized with binwidth
  last_bin_center: 425
  first_bin_center: 7.5
  plot_log: 1
  variable: "p_T^H"
  y_unit: "(fb/GeV)"
  x_unit: "(GeV)"
  x_lim: [0, 500]
  y_lim: [-1,3]
  y_lim_top: 500
  overflow: 500

