#!/bin/sh
ulimit -s unlimited
set -e
cd /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src
export SCRAM_ARCH=slc7_amd64_gcc700
source /cvmfs/cms.cern.ch/cmsset_default.sh
eval `scramv1 runtime -sh`
cd /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/runFitsxsec_xsec

if [ $1 -eq 0 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 0 --lastPoint 0 -n _profile1D_syst_xsec_r_top.POINTS.0.0
fi
if [ $1 -eq 1 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 1 --lastPoint 1 -n _profile1D_syst_xsec_r_top.POINTS.1.1
fi
if [ $1 -eq 2 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 2 --lastPoint 2 -n _profile1D_syst_xsec_r_top.POINTS.2.2
fi
if [ $1 -eq 3 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 3 --lastPoint 3 -n _profile1D_syst_xsec_r_top.POINTS.3.3
fi
if [ $1 -eq 4 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 4 --lastPoint 4 -n _profile1D_syst_xsec_r_top.POINTS.4.4
fi
if [ $1 -eq 5 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 5 --lastPoint 5 -n _profile1D_syst_xsec_r_top.POINTS.5.5
fi
if [ $1 -eq 6 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 6 --lastPoint 6 -n _profile1D_syst_xsec_r_top.POINTS.6.6
fi
if [ $1 -eq 7 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 7 --lastPoint 7 -n _profile1D_syst_xsec_r_top.POINTS.7.7
fi
if [ $1 -eq 8 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 8 --lastPoint 8 -n _profile1D_syst_xsec_r_top.POINTS.8.8
fi
if [ $1 -eq 9 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 9 --lastPoint 9 -n _profile1D_syst_xsec_r_top.POINTS.9.9
fi
if [ $1 -eq 10 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 10 --lastPoint 10 -n _profile1D_syst_xsec_r_top.POINTS.10.10
fi
if [ $1 -eq 11 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 11 --lastPoint 11 -n _profile1D_syst_xsec_r_top.POINTS.11.11
fi
if [ $1 -eq 12 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 12 --lastPoint 12 -n _profile1D_syst_xsec_r_top.POINTS.12.12
fi
if [ $1 -eq 13 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 13 --lastPoint 13 -n _profile1D_syst_xsec_r_top.POINTS.13.13
fi
if [ $1 -eq 14 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 14 --lastPoint 14 -n _profile1D_syst_xsec_r_top.POINTS.14.14
fi
if [ $1 -eq 15 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 15 --lastPoint 15 -n _profile1D_syst_xsec_r_top.POINTS.15.15
fi
if [ $1 -eq 16 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 16 --lastPoint 16 -n _profile1D_syst_xsec_r_top.POINTS.16.16
fi
if [ $1 -eq 17 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 17 --lastPoint 17 -n _profile1D_syst_xsec_r_top.POINTS.17.17
fi
if [ $1 -eq 18 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 18 --lastPoint 18 -n _profile1D_syst_xsec_r_top.POINTS.18.18
fi
if [ $1 -eq 19 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 19 --lastPoint 19 -n _profile1D_syst_xsec_r_top.POINTS.19.19
fi
if [ $1 -eq 20 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 20 --lastPoint 20 -n _profile1D_syst_xsec_r_top.POINTS.20.20
fi
if [ $1 -eq 21 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 21 --lastPoint 21 -n _profile1D_syst_xsec_r_top.POINTS.21.21
fi
if [ $1 -eq 22 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 22 --lastPoint 22 -n _profile1D_syst_xsec_r_top.POINTS.22.22
fi
if [ $1 -eq 23 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 23 --lastPoint 23 -n _profile1D_syst_xsec_r_top.POINTS.23.23
fi
if [ $1 -eq 24 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 24 --lastPoint 24 -n _profile1D_syst_xsec_r_top.POINTS.24.24
fi
if [ $1 -eq 25 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 25 --lastPoint 25 -n _profile1D_syst_xsec_r_top.POINTS.25.25
fi
if [ $1 -eq 26 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 26 --lastPoint 26 -n _profile1D_syst_xsec_r_top.POINTS.26.26
fi
if [ $1 -eq 27 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 27 --lastPoint 27 -n _profile1D_syst_xsec_r_top.POINTS.27.27
fi
if [ $1 -eq 28 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 28 --lastPoint 28 -n _profile1D_syst_xsec_r_top.POINTS.28.28
fi
if [ $1 -eq 29 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 29 --lastPoint 29 -n _profile1D_syst_xsec_r_top.POINTS.29.29
fi
if [ $1 -eq 30 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 30 --lastPoint 30 -n _profile1D_syst_xsec_r_top.POINTS.30.30
fi
if [ $1 -eq 31 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 31 --lastPoint 31 -n _profile1D_syst_xsec_r_top.POINTS.31.31
fi
if [ $1 -eq 32 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 32 --lastPoint 32 -n _profile1D_syst_xsec_r_top.POINTS.32.32
fi
if [ $1 -eq 33 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 33 --lastPoint 33 -n _profile1D_syst_xsec_r_top.POINTS.33.33
fi
if [ $1 -eq 34 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 34 --lastPoint 34 -n _profile1D_syst_xsec_r_top.POINTS.34.34
fi
if [ $1 -eq 35 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 35 --lastPoint 35 -n _profile1D_syst_xsec_r_top.POINTS.35.35
fi
if [ $1 -eq 36 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 36 --lastPoint 36 -n _profile1D_syst_xsec_r_top.POINTS.36.36
fi
if [ $1 -eq 37 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 37 --lastPoint 37 -n _profile1D_syst_xsec_r_top.POINTS.37.37
fi
if [ $1 -eq 38 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 38 --lastPoint 38 -n _profile1D_syst_xsec_r_top.POINTS.38.38
fi
if [ $1 -eq 39 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 39 --lastPoint 39 -n _profile1D_syst_xsec_r_top.POINTS.39.39
fi
if [ $1 -eq 40 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 40 --lastPoint 40 -n _profile1D_syst_xsec_r_top.POINTS.40.40
fi
if [ $1 -eq 41 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 41 --lastPoint 41 -n _profile1D_syst_xsec_r_top.POINTS.41.41
fi
if [ $1 -eq 42 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 42 --lastPoint 42 -n _profile1D_syst_xsec_r_top.POINTS.42.42
fi
if [ $1 -eq 43 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 43 --lastPoint 43 -n _profile1D_syst_xsec_r_top.POINTS.43.43
fi
if [ $1 -eq 44 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 44 --lastPoint 44 -n _profile1D_syst_xsec_r_top.POINTS.44.44
fi
if [ $1 -eq 45 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 45 --lastPoint 45 -n _profile1D_syst_xsec_r_top.POINTS.45.45
fi
if [ $1 -eq 46 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 46 --lastPoint 46 -n _profile1D_syst_xsec_r_top.POINTS.46.46
fi
if [ $1 -eq 47 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 47 --lastPoint 47 -n _profile1D_syst_xsec_r_top.POINTS.47.47
fi
if [ $1 -eq 48 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 48 --lastPoint 48 -n _profile1D_syst_xsec_r_top.POINTS.48.48
fi
if [ $1 -eq 49 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 49 --lastPoint 49 -n _profile1D_syst_xsec_r_top.POINTS.49.49
fi
if [ $1 -eq 50 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 50 --lastPoint 50 -n _profile1D_syst_xsec_r_top.POINTS.50.50
fi
if [ $1 -eq 51 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 51 --lastPoint 51 -n _profile1D_syst_xsec_r_top.POINTS.51.51
fi
if [ $1 -eq 52 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 52 --lastPoint 52 -n _profile1D_syst_xsec_r_top.POINTS.52.52
fi
if [ $1 -eq 53 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 53 --lastPoint 53 -n _profile1D_syst_xsec_r_top.POINTS.53.53
fi
if [ $1 -eq 54 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 54 --lastPoint 54 -n _profile1D_syst_xsec_r_top.POINTS.54.54
fi
if [ $1 -eq 55 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 55 --lastPoint 55 -n _profile1D_syst_xsec_r_top.POINTS.55.55
fi
if [ $1 -eq 56 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 56 --lastPoint 56 -n _profile1D_syst_xsec_r_top.POINTS.56.56
fi
if [ $1 -eq 57 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 57 --lastPoint 57 -n _profile1D_syst_xsec_r_top.POINTS.57.57
fi
if [ $1 -eq 58 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 58 --lastPoint 58 -n _profile1D_syst_xsec_r_top.POINTS.58.58
fi
if [ $1 -eq 59 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 59 --lastPoint 59 -n _profile1D_syst_xsec_r_top.POINTS.59.59
fi
if [ $1 -eq 60 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 60 --lastPoint 60 -n _profile1D_syst_xsec_r_top.POINTS.60.60
fi
if [ $1 -eq 61 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 61 --lastPoint 61 -n _profile1D_syst_xsec_r_top.POINTS.61.61
fi
if [ $1 -eq 62 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 62 --lastPoint 62 -n _profile1D_syst_xsec_r_top.POINTS.62.62
fi
if [ $1 -eq 63 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 63 --lastPoint 63 -n _profile1D_syst_xsec_r_top.POINTS.63.63
fi
if [ $1 -eq 64 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 64 --lastPoint 64 -n _profile1D_syst_xsec_r_top.POINTS.64.64
fi
if [ $1 -eq 65 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 65 --lastPoint 65 -n _profile1D_syst_xsec_r_top.POINTS.65.65
fi
if [ $1 -eq 66 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 66 --lastPoint 66 -n _profile1D_syst_xsec_r_top.POINTS.66.66
fi
if [ $1 -eq 67 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 67 --lastPoint 67 -n _profile1D_syst_xsec_r_top.POINTS.67.67
fi
if [ $1 -eq 68 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 68 --lastPoint 68 -n _profile1D_syst_xsec_r_top.POINTS.68.68
fi
if [ $1 -eq 69 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 69 --lastPoint 69 -n _profile1D_syst_xsec_r_top.POINTS.69.69
fi
if [ $1 -eq 70 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 70 --lastPoint 70 -n _profile1D_syst_xsec_r_top.POINTS.70.70
fi
if [ $1 -eq 71 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 71 --lastPoint 71 -n _profile1D_syst_xsec_r_top.POINTS.71.71
fi
if [ $1 -eq 72 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 72 --lastPoint 72 -n _profile1D_syst_xsec_r_top.POINTS.72.72
fi
if [ $1 -eq 73 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 73 --lastPoint 73 -n _profile1D_syst_xsec_r_top.POINTS.73.73
fi
if [ $1 -eq 74 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 74 --lastPoint 74 -n _profile1D_syst_xsec_r_top.POINTS.74.74
fi
if [ $1 -eq 75 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 75 --lastPoint 75 -n _profile1D_syst_xsec_r_top.POINTS.75.75
fi
if [ $1 -eq 76 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 76 --lastPoint 76 -n _profile1D_syst_xsec_r_top.POINTS.76.76
fi
if [ $1 -eq 77 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 77 --lastPoint 77 -n _profile1D_syst_xsec_r_top.POINTS.77.77
fi
if [ $1 -eq 78 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 78 --lastPoint 78 -n _profile1D_syst_xsec_r_top.POINTS.78.78
fi
if [ $1 -eq 79 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 79 --lastPoint 79 -n _profile1D_syst_xsec_r_top.POINTS.79.79
fi
if [ $1 -eq 80 ]; then
  combine --floatOtherPOIs 1 -t -1 -P r_top --algo grid --alignEdges 1 --redefineSignalPOIs r_top,r_VBF,r_VH,r_ggH --setParameters r_ggH=1,r_top=1,r_VH=1,r_VBF=1 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_BOUND --saveSpecifiedNuis all --saveInactivePOI 1 --fastScan --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d /afs/cern.ch/user/f/fderiggi/AC/CMSSW_10_2_13/src/flashggFinalFit/Combine/Datacard_xsec.root --setParameterRanges r_ggH=0.0,2.0:r_VBF=0.0,2.0:r_VH=0.0,3.0:r_top=0.0,4.0 --points 81 --firstPoint 80 --lastPoint 80 -n _profile1D_syst_xsec_r_top.POINTS.80.80
fi

